apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: miniapi-prod
spec:
  secretName: miniapi-production-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - 34.140.97.51.nip.io
    - test-api.nip.io